### ISSUE TITLE
Broken EggNOG URL

### ISSUE THREAD

**Issue by nelas** [harta55/EnTAP#10]
Hi,

I just ran the config step and it failed to download the [eggnog4.clustered_proteins.fa.gz](https://github.com/harta55/EnTAP/blob/99e0214b22f28a76a7e2f5dc6b2ad067818e68ff/src/database/EggnogDatabase.h#L91) because [the URL](http://eggnog5.embl.de/download/latest/eggnog-mapper-data/eggnog4.clustered_proteins.fa.gz) is broken.

Is this the correct one? http://eggnog5.embl.de/download/eggnog_4.5/eggnog-mapper-data/eggnog4.clustered_proteins.fa.gz

Cheers

**Comment by harta55** [comment]
Apologies for the delay. Yes, looks like their links have changed. I will update these. Thanks for bringing this up.

**Comment by harta55** [comment]
It seems things moved around a bit more than I expected. These are correct:
http://eggnog5.embl.de/download/eggnog_4.1/eggnog-mapper-data/eggnog.db.gz
http://eggnog5.embl.de/download/eggnog_4.1/eggnog-mapper-data/eggnog_proteins.dmnd.gz
http://eggnog5.embl.de/download/eggnog_4.1/eggnog-mapper-data/eggnog4.clustered_proteins.fa.gz

If you pull the latest release it will have these. I  re-released the newest version to avoid confusion

**Comment by xiekunwhy** [comment]
Hi,

EnTAP compatible with eggnog5 now?

Best,
Kun
