### ISSUE TITLE
source code link broken

### ISSUE THREAD

**Issue by juliayork** [harta55/enTAP#105]
This link is not working: https://gitlab.com/EnTAP/EnTAP/tags

Which is what is suggested to download the source code on this page: https://entap.readthedocs.io/en/v1.4.0/Getting_Started/Installation/Installation_From_Source_Code/installation_from_source_code.html

**Comment by harta55** [comment]
Hi! Please use this for latest source code:
https://gitlab.com/PlantGenomicsLab/EnTAP
Docs will be updated shortly
