### ISSUE TITLE
Add --no_refine_starts option for Transdecoder

### ISSUE THREAD

**Issue by Aciole-David** [harta55/EnTAP#24]
Hello,
Thanks for the amazing work on EnTAP!

Performing some tests to setup EnTAP on my machines:
Transdecoder got stuck in the start-refinement step using the test data (trinity.fnn) and frame selection (--runP).
If I run Transdecoder outside EnTAP I got the same error, but I can add the --no_refine_starts option, then it run without any errors.
Of course this may be an specific characteristic of the input, but...
Is it somehow possible to pass --no_refine_starts to EnTAP?

Thanks again
Cheers

**Comment by harta55** [comment]
Hello!

Added support for this in a new version 0.10.6. You will need to add the command "transdecoder-no-refine-starts=true" to the ini file (or pull from the latest repo).

**Comment by Aciole-David** [comment]
> Hello!
> 
> Added support for this in a new version 0.10.6. You will need to add the command "transdecoder-no-refine-starts=true" to the ini file (or pull from the latest repo).

Awesome!
