### ISSUE TITLE
What is the actual information for "KEGG Terms (EggNOG)"?

### ISSUE THREAD

**Issue by Aciole-David** [harta55/EnTAP#27]
Hello,
Does the "KEGG Terms (EggNOG)" column within the final annotation tsv correspond to kegg pathway IDs or Kegg ortholog IDs (KO)?
Thanks

**Comment by Aciole-David** [comment]
@harta55 Could you please help me up on this?

**Comment by harta55** [comment]
Slipped by me sorry! These are pulled from EggNOG v4.1 (updating shortly to newest version) which I believe are the pathways

**Comment by Aciole-David** [comment]
Don't worry. Thank you very much!
