### ISSUE TITLE
Error in reading serialized database!

### ISSUE THREAD

**Issue by atice** [harta55/EnTAP#3]
I am trying to install EnTAP on my lab's server and have run into problems when trying to verify the main execution stage with the test data. I have confirmed our server has all the necessary dependencies installed, and received no errors through the configuration stages. I also did not get an error when I ran the configuration step on the test database. However, when I try and run the entire pipeline on the test data using the command:

EnTAP --runP -i test_data/trinity.fnn -d test_data/swiss_prot_test.dmnd 

I get the following:

Error code: 72
Error code not recognized.
Unable to generate EnTAP database from paths given

and the debug file gives:

Thu May  3 09:02:44 2018: Verifying EnTAP database...
Thu May  3 09:02:44 2018: Reading serialized database from: /mnt/scratch3/db-scratch3/EnTAP/outfiles/bin/entap_database.bin
Thu May  3 09:02:44 2018: Error in reading serialized database!
Thu May  3 09:02:44 2018: Error code: 72
Error code not recognized.
Unable to generate EnTAP database from paths given
Thu May  3 09:02:44 2018: End - EnTAP
Thu May  3 09:02:44 2018: Killing Object - FileSystem
Thu May  3 09:02:44 2018: Killing object - UserInput

I have checked that all paths in my config file are correct. I have also tried deleting the entap binary database downloaded upon configuration and retrieving it manually, but I get the same error. Any help would be much appreciated. Please let me know if I have left out some information that you need/would make it easier for you to resolve this issue.

Alex

**Comment by harta55** [comment]
Hello,

This is likely an incompatibility issue with the database and whichever version of Boost Libraries you are using (ensure you're using atleast the specified version in the docs). Just delete the file and use the - -data-generate flag when running configuration and it will index the database locally with your version of Boost. Let me know if this resolves the issue!

**Comment by atice** [comment]
Thank you so much. The issue has been resolved.


Alex



*Alexander K. Tice, M.Sc.*
Ph.D. Student
Mississippi State University
026 Harned Hall
Lab Telephone: 662-325-4008

**Comment by chani118** [comment]
I am having a similar problem. I am getting 
Error code: 72
Error code not recognized.
Unable to initialize EnTAP database

EnTAP Database Error: Unable to read Serialized EnTAP database: Failed to read 1565 bytes from input stream! Read 1402

I followed the above advice and could not get it to work. Do you have any other suggestions.
Thank you,
Chani
