### ISSUE TITLE
Error Code 161 (EggNog?)

### ISSUE THREAD

**Issue by Aciole-David** [harta55/EnTAP#30]
I received this error in a CentOS HPC SLURM:

----------------------------------------------------
Here are a few ways to help diagnose some general issues:
	1. Check the (detailed) printed error message below
	2. Review the .err files of the execution stage (they will
		be in the directory for whatever stage you failed
	3. Check the debug.txt file that is printed after execution
	4. Ensure your paths/inputs are correct in entap_config.ini
		and log_file.txt (this will show your inputs)
----------------------------------------------------
Error code: 161
Ensure that your EggNOG run finished successfully and the files are not empty.
Error querying database: database is locked

real	831m39.899s
user	14893m42.664s
sys	893m7.080s

Any guess?
Thanks

**Comment by harta55** [comment]
Is anything else on your system accessing that eggnog database at the same time?

**Comment by Aciole-David** [comment]
> Is anything else on your system accessing that eggnog database at the same time?

I'm afraid not. Any guess?

**Comment by harta55** [comment]
Issue no longer relevant due to latest EnTAP changes
