### ISSUE TITLE
No alignments in 1 diamond database halts entire pipeline

### ISSUE THREAD

**Issue by dy-lin** [harta55/EnTAP#33]
Error code: 140

When given multiple diamond-configured databases to EnTAP, all of them must have alignments in order to proceed in the pipeline. However, I think the pipeline should be designed so that it is able to proceed if at least 1 database has alignments, instead of halting entirely with error code 140.

[debug_2021Y2M25D-20h40m12s.txt](https://github.com/harta55/EnTAP/files/6087123/debug_2021Y2M25D-20h40m12s.txt)

**Comment by harta55** [comment]
Agreed, this was changed in the latest version 0.10.8. The pipeline will now not halt if one database has no alignments. If there are not any alignments across all databases, it will halt.
