### ISSUE TITLE
Issues with EnTAP v0.10.8 documentation + configuration bugs?

### ISSUE THREAD

**Issue by vragh** [harta55/EnTAP#37]
Hi EnTAP devs and users,

I just want to provide some feedback regarding the documentation of the tool and the configuration process as it stands for `EnTAP v0.10.8`.

**Documentation issues:**

Under the [`Installation` section](https://entap.readthedocs.io/en/latest/Getting_Started/installation.html), the documentation does not clearly indicate where `EnTAP` should be downloaded from. The first time downloading the tool itself is even mentioned is in this sentence "If you have downloaded the full repository from the GitLab page," towards the end of the [section `Pipeline Software`](https://entap.readthedocs.io/en/latest/Getting_Started/installation.html#pipeline-software). This then leads on to the sections on compiling/installing `Diamond` and `RSEM`. However, thereafter, there is a [section called `EnTAP Installation`](https://entap.readthedocs.io/en/latest/Getting_Started/installation.html#entap-installation). This section opens with:

```
Once dependencies and pipeline software have been installed, you can now continue to install EnTAP!

First, download and extract the latest release(tagged) version from GitLab: https://gitlab.com/EnTAP/EnTAP/tags
```

But this doesn't make any sense? Why would one download the `GitLab` or `GitHub` repo, compile and install the copies of `Diamond` and `RSEM` included there, and then download a release once again separately?

Also, the [section `RSEM Installation`](https://entap.readthedocs.io/en/latest/Getting_Started/installation.html#rsem-installation) indicates that `RSEM` and `EBSeq` need to be compiled. However, running `make` as indicated within said directories under `EnTAP v0.10.8` throws `make: *** No targets specified and no makefile found.  Stop.`. Further, (all?) `RSEM` components appear to be present already (and are already compiled)?

**Configuration issues:**

- As indicated by the configuration log file some general errors (because of missing defaults in the `.ini` file?):
```
NO, no alignment file specified from user
Determining if we want to run frame selection...
ERROR Unable to determine, nullptr!

```
- There are a lot of places where paths end up with double slashes (especially worrisome w.r.t. `--out-dir` paths):
```
Success, file saved to: /some/entap/path/temp//entap_database.bin.gz
```
- Nothing gets printed to the terminal during the configuration stage. It would be nice if the log or debug file's contents could be presented for the user to see. I had no clue what was happening until I opened another terminal and noticed the log and debug files. It also doesn't help that it is not readily apparent that these files are config-related (they just have the generic `runP/runN` style naming).

**Test Data stage issues:**

Trying to execute the test config run [as indicated here](https://entap.readthedocs.io/en/latest/Getting_Started/test_data.html) makes `EnTAP` terminate with the following error:

```
/path/to/EnTAP --config -d /path/to/test_data/swiss_prot_test.fasta --out-dir /path/to/test_data/swiss_prot_test.fasta/test_data --ini /path/to/entap_config.ini
Error code: 36


EnTAP Database Error: Unable to download EnTAP Serial Database from https://treegenesdb.org/FTP/EnTAP/v0.10.8/databases/entap_database.bin.gz
Unable to get file
/path/to/test_data/swiss_prot_test.fasta/test_data/temp//entap_database.bin.gz: Not a directory
```

**Comment by harta55** [comment]
Hi vragh,
Thanks for the input on the documentation, will get that squared away and a bit clearer. You have the option to use the pre-packaged versions that come with the EnTAP package, or use the versions you may have installed locally. Concerning RSEM, looks like the Makefile is not included in the EnTAP package. I'll update this. Thanks!

Your configuration seems to have succeeded without issue? The debug print you mentioned will not terminate the configuration stage and is more of a warning.

There is a known bug with the test data. Although, you should not be failing the configuration stage (only execution/run). Please send over the full debug file when you get the chance.

**Comment by vragh** [comment]
Hi @harta55 ,

Thanks for the quick reply.

1. So should i install `RSEM` manually then? What about the `R` package `EBSeq`?
2. The configuration stage did complete actually (and the log file indicated that it was successful). Apologies for not mentioning that.
3. Is this a bug with the test data though? That error seems to imply something else entirely? Also, this particular error code (`36`) is not documented in the [section on error codes](https://entap.readthedocs.io/en/latest/Running_EnTAP/troubleshooting.html#error-codes) yet.
4. Would you recommend using one of the older versions of `EnTAP` at this point?

**Comment by harta55** [comment]
1) Yes, RSEM can be installed here with instructions https://github.com/deweylab/RSEM

3) Can you send over the full debug file?

4) You likely shouldn't see any other issues with this version, but if you run into anything else the previous version (0.10.7) has been in use for some time now that you could switch to. This will require re-configuring EnTAP though.

**Comment by vragh** [comment]
Here's the debug file for the configuration stage. I've anonymized a couple of paths here and there.
[debug_2021Y4M19D-21h44m1s.txt](https://github.com/harta55/EnTAP/files/6369386/debug_2021Y4M19D-21h44m1s.txt)

Then I suppose i will stick with `v0.10.7` at this point in time.

**Comment by MattHuff** [comment]
Good Morning,

I am also running into issues with configuring EnTAP v10.8. In particular, I am having difficulties installing DIAMOND. I followed the documentation on [the EnTAP ReadtheDocs](https://entap.readthedocs.io/en/latest/Getting_Started/installation.html), and I am only able to get up to the `make` step. After that, I get the following error:

```[100%] Linking CXX executable diamond
CMakeFiles/diamond.dir/src/run/benchmark.cpp.o: In function `benchmark_swipe(Sequence_set const&)':
benchmark.cpp:(.text+0x1a7c): undefined reference to `Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&)'
CMakeFiles/diamond.dir/src/align/align_target.cpp.o: In function `Query_mapper::align_target(unsigned long, Statistics&)':
align_target.cpp:(.text+0x103f): undefined reference to `Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/diamond.dir/build.make:1034: diamond] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/diamond.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Has anyone else run into this issue? I imagine this issue will be on DIAMOND's end rather than EnTAP, but I would like to know if this has been solved by anyone else.

**Comment by vragh** [comment]
@MattHuff could be a `gcc` issue? Which version of the compiler are you using? I just got the latest versions of everything needed for the installation (and execution) off of `conda` and threw them all into an environment.

**Comment by MattHuff** [comment]
@vragh This is the version of gcc I am currently running:
```gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by vragh** [comment]
> @vragh This is the version of gcc I am currently running:
> 
> ```
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> Our server uses Spack modules and has a newer version of gcc available, but I am still unable to `make` the diamond executable.

What version of `CMake` are you using? I'd try installing the latest version (e.g., via `conda`) and attempting the installation again thereafter. What ended up working for me was using the latest versions of all the tools that @harta55 had specified in the documentation.

**Comment by MattHuff** [comment]
We run version 3.19.1 of CMake through a module. I installed CMake version 3.20.2 within a conda environment, as well as an earlier attempt with version 3.18.4 through PIP, but both versions gave me the same error after clearing the `bin` folder and rerunning the process from the beginning.

Also, in looking at my previous message, I did not actually catch the version of GCC we use; my apologies! We use `gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)` by default. We also have version 10.2.0 available through a module, but running `make` with that version does not work either.

**Comment by vragh** [comment]
@MattHuff that's great to hear! And I agree, it'd be nice to see what the dev(s) have to say.

So you got `EnTAP v0.10.8` up and running then? I'm just asking before I switch over from `v0.10.7`

**Comment by vragh** [comment]
@harta55 some more feedback for you, w.r.t. `v0.10.8`.

**Additional notes about the documentation:**

1. It'd be very helpful if the a section on setting up the configuration file were to be included. For instance, it's left up to the user to figure out that they must set the paths to the databases in the config file before/after downloading them.
2. Would it not make sense to have the entire test data section done with BEFORE the configuration stage? IMHO it makes more sense to have the documentation suggest that the users first set up a full config file (database paths included) for the test data, verify that, and then walk them through setting up a final config file with the "real" databases.

**Some notes about the execution stage:**

1. Contaminants are flagged for/from the similarity search. Could you confirm whether this extends to the GO transfer process also?
2. The configuration file indicates query and target coverage thresholds for the similarity search. I think adding a note that the queries are the input transcriptomic sequences would be helpful. Additionally, aren't the current default threshold values very permissive?

**Comment by xaramillo** [comment]
Days ago I tried to compile RSEM and diamond based on v10.0.7 Makefiles (This is the last version I saw they're in each folder). The installation was succesfull on RSEM only.

**Comment by harta55** [comment]
Hi @vragh, I agree with your comments. We are currently working on a Dockerized version of EnTAP to ease installation a bit. 

Answers to your questions above:
1) I'm not sure I understand what you mean by 'GO transfer process'?
2) That is correct, will specify in docs. They are permissive for default values. We have seen varied preferences here so decided to keep it at that.

**Comment by vragh** [comment]
@harta55 why `docker` though? That would make deploying the tool a pain (or impossible) on HPC environments. Wouldn't `singularity` be the better option here?

1. By "GO transfer process" I meant the search against `EggNOG` DB.
2. Would you recommend leaving the coverage values at the defaults or is it better for the user to alter them?

**Comment by harta55** [comment]
Docs, test data, and Docker/Singularity have since been updated. Closing ticket
