### ISSUE TITLE
Using conda with EnTAP

### ISSUE THREAD

**Issue by MattHuff** [harta55/EnTAP#38]
I have run into issues creating the DIAMOND 0.9.9 executable within the EnTAP 0.10.8 library. When I attempt to run `make` on the version of DIAMOND, I get this error:

```
CMakeFiles/diamond.dir/src/run/benchmark.cpp.o: In function `benchmark_swipe(Sequence_set const&)':
benchmark.cpp:(.text+0x1a7c): undefined reference to `Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&)'
CMakeFiles/diamond.dir/src/align/align_target.cpp.o: In function `Query_mapper::align_target(unsigned long, Statistics&)':
align_target.cpp:(.text+0x103f): undefined reference to `Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/diamond.dir/build.make:1034: diamond] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/diamond.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

I have gotten DIAMOND version 0.9.14 installed and working within a conda environment. What steps, if any, do I need to take to allow EnTAP to work with the conda installation of DIAMOND? Please let me know as soon as you are able.

**Comment by vragh** [comment]
@harta55 can correct me if if I'm wrong but all you need to do is specific the path to the `diamond` executable (so `/path/to/conda/diamond`) in the `EnTAP` `config.ini` file, and it should be good to go.

**Comment by harta55** [comment]
Correct, that should do the trick as far as using DIAMOND. Let me know if that works for you @MattHuff. However, if you are having compilation problems with DIAMOND I may not be able to help

**Comment by MattHuff** [comment]
Thank you for the feedback. I figured out what was wrong with my config file and was able to utilize the version of DIAMOND available through SPACK. The initial steps of configuring EnTAP worked without issue for me, but now EnTAP is failing for me when trying to run DIAMOND:

```
Error code: 141
Ensure you have specified the proper path to the executable. Additionally, the database you are specifying is configured for DIAMOND (.dmnd).
Error with database located at: bin/uniprot_sprot.dmnd
DIAMOND Error: diamond v2.0.4.142 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: No such file or directory
Error: Error opening temporary file ./Fraxinus_albicans_EnTAP//similarity_search/DIAMOND/diamond-tmp-Z6zwNi
```

The configuration file points to the same version of DIAMOND, so it should not be an issue with a different version of DIAMOND being unable to read the databases. I'm not sure if the database file has a quick way of checking for any major errors that would cause this to occur. Is this something you have seen before when running EnTAP? Please let me know as soon as you are able.
