### ISSUE TITLE
Too many gene(transcript)-GO pairs

### ISSUE THREAD

**Issue by xiekunwhy** [harta55/EnTAP#41]
Hi,

I have two quetions,
1. Results looks like abnormal.

I have tried to use entap to annotate 2 plant species, and the results looks like abnormal because there are too many gene(transcipt)-GO pairs (final_annotations_no_contam_lvl0_enrich_geneid_go.tsv),
**Species 1 (refseq predicted genes), 50547 genes**
entap gene-GO pairs: 2271833
blast2go basic gene-GO pairs: 211997
intersection: 108785

**Species 2 (Denovo RNA-seq), 122666 transcripts**
entap transcript-GO pairs: 3091852
blast2go basic transcript-GO pairs: 186459
intersection: 94523

entap gene/transcript-GO pair number are 10-20 times larger than blast2go basic, is it possible? And many are not in the intersections, entap produce too many false positive results?
Here is the config file I was used
[entap_config.ini.txt](https://github.com/harta55/EnTAP/files/6417324/entap_config.ini.txt)
And the command line is
EnTAP --runN --no-check -i all.fa -d ./NR/20210318/diamond/plant.dmnd --ini entap_config.ini -t 4

2. Entap still can not use eggnog v5.0 ?

Best,
Kun

**Comment by harta55** [comment]
It is difficult to say depending on where these GO pairs came from. Were they all from EggNOG alignments? Also, were any duplicates printed?

**Comment by xiekunwhy** [comment]
Hi @harta55 

Yes, all GO information were from EggNOG alignments, and without any duplicates printed.

Best,
Kun

**Comment by harta55** [comment]
Closing out old issue that has not occurred again. GO terms were pulled from multiple sources including Eggnog/Similarity searching (if mapping exist). Results may be normal depending on run
