### ISSUE TITLE
Parse error when configuring

### ISSUE THREAD

**Issue by fka21** [harta55/EnTAP#42]
Hello,

I am trying to install EnTAP on my computer, but when reaching the configuration step it somehow does not recognise the --ini flag. I am using the latest version of it (v0.10.8-beta) and followed the installation steps. 

`PARSE ERROR: Argument: --ini
             Couldn't find match for argument`

Do you have any ideas what could be the problem here? 

Thank you in advance!

Cheers

**Comment by harta55** [comment]
Hello,

Likely just some formatting issue in your ini file. Can you send it over or check around if there are any unusual formatting in yours compared to the one in the repo?

**Comment by fka21** [comment]
Hello,

Thank you for the reply! Had to rename the ini file in order to upload, apart from that I did not change anything about it. 
[entap_config.ini.txt](https://github.com/harta55/EnTAP/files/6607584/entap_config.ini.txt)

I used the following command for the configuration step:
`EnTAP --config -d /Users/ferenckagan/Documents/Bioinformatic_analysis/EnTAP-v0.10.8-beta/Databases/uniprot_trembl.fasta -d /Users/ferenckagan/Documents/Bioinformatic_analysis/EnTAP-v0.10.8-beta/Databases/uniprot_sprot.fasta --out-dir /Users/ferenckagan/Documents/Bioinformatic_analysis/EnTAP-v0.10.8-beta/ -t 2 --ini /Users/ferenckagan/Documents/Bioinformatic_analysis/EnTAP-v0.10.8-beta/`

**Comment by harta55** [comment]
Issue has not been reported in several versions. Closing until issue is reported again.
