### ISSUE TITLE
BUG: EnTAP v0.10.8 duplicate seq entries in final_results/*.fnn and *.faa

### ISSUE THREAD

**Issue by hans-vg** [harta55/EnTAP#44]
I went to run BUSCO on the output of the results, but it complained about a duplicate entry. After checking the FASTA file, I noticed every entry is duplicated. 

I was able to remove the duplicates using seqkit rmdup though

**Comment by UConnBBC** [comment]
Confirmed this issue with the latest version - produces duplicates in several output files

**Comment by harta55** [comment]
Issue has been resolved in latest release v0.10.9.
