### ISSUE TITLE
Not downloading databases during config step

### ISSUE THREAD

**Issue by incoreygible** [harta55/EnTAP#46]
I am getting an error during the config step where it's failing to download the databases:

```
EnTAP --config
Error code: 10

EggNOG DIAMOND database was not found at: /bin/eggnog_proteins.dmnd
The DIAMOND test run failed.
```

I have Eggnog mapper and Diamond both installed and am connected to the internet. I'm unsure where the issue is arising if this step is supposed to download databases first before looking for them. Is there a simple way to fix this? Apologies if I'm missing something obvious, I'm new to these kinds of tools.

**Comment by incoreygible** [comment]
I downloaded the diamond database separately into a different directory, and edited the path in the config file to point directly there:

```
#Path to EggNOG DIAMOND configured database that was generated during the Configuration stage.
#type:string
eggnog-dmnd=$HOME/miniconda3/lib/python3.9/site-packages/data/eggnog_proteins.dmnd
```

I am getting the same error, even though the .dmnd is clearly there.

```
Error code: 10

EggNOG DIAMOND database was not found at: $HOME/miniconda3/lib/python3.9/site-packages/data/eggnog_proteins.dmnd
The DIAMOND test run failed.
```

**Comment by harta55** [comment]
Closing as this issue is no longer relevant with latest version of EnTAP
