### ISSUE TITLE
 Time savers: Re-running the pipeline

### ISSUE THREAD

**Issue by AlexGaithuma** [harta55/EnTAP#47]
I have a problem with core dump during the Eggnog ontology step.

Every time I encounter this problem and re-run the pipeline,
Even though all the other processes have completed,
the pipeline starts at the transcriptome file.... which can be skipped

    Mon Mar  7 10:01:41 2022: Graphing is supported
    Mon Mar  7 10:01:41 2022: Reading serialized database from: /data1/IxoSca/database/bin/entap_database.bin
     Of type: 2
    Mon Mar  7 10:02:09 2022: STATE - EXPRESSION FILTERING
    Mon Mar  7 10:02:09 2022: Determining if we want to run expression analysis
    Mon Mar  7 10:02:09 2022: NO, no alignment file specified from user
    Mon Mar  7 10:02:09 2022: No alignment file specified, skipping expression analysis
    Mon Mar  7 10:02:09 2022: verifying state...
    Mon Mar  7 10:02:09 2022: STATE - FRAME SELECTION
    Mon Mar  7 10:02:09 2022: Determining if we want to run frame selection...
    Mon Mar  7 10:02:09 2022: NO Protein sequences input AND runP, skipping frame selection
    Mon Mar  7 10:02:09 2022: verifying state...
    Mon Mar  7 10:02:09 2022: Beginning to copy final transcriptome to be used...
    Mon Mar  7 10:02:09 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/transcriptomes//Trinity_final.fasta
    Mon Mar  7 10:02:10 2022: FINAL transcriptome generated to: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/transcriptomes//Trinity_final.fasta
    Mon Mar  7 10:02:10 2022: verifying state...

Then proceeds to delete previous files from similarity search which is not my problematic step....this takes hours to repeat and is unnecessary to my analysis.

    Mon Mar  7 10:02:10 2022: STATE - SIMILARITY SEARCH
    Mon Mar  7 10:02:10 2022: Spawn Object - SimilaritySearch
    Mon Mar  7 10:02:10 2022: opendir: Path could not be read: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/figures/
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_species_bar.txt
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_summary_bar.txt
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_contam_bar.txt
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_contam_bar.png
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_species_bar.png
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/figures/_summary_bar.png
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam_lvl0.tsv
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam_lvl1.tsv
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam_lvl2.tsv
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam_lvl3.tsv
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam.faa
    Mon Mar  7 10:02:10 2022: Deleting file at: /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/processed//Refseq/best_hits_contam.fnn
    Mon Mar  7 10:02:12 2022: Spawn Object - ModDiamond
    Mon Mar  7 10:02:12 2022: Verifying previous execution of database: /data1/IxoSca/database/bin/Refseq.dmnd...
    Mon Mar  7 10:02:12 2022: File for database Refseq exists, skipping... /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/blastp_Trinity_final_Refseq.out
    Mon Mar  7 10:02:12 2022: Verifying previous execution of database: /data1/IxoSca/database/bin/nr.dmnd...
    Mon Mar  7 10:02:12 2022: File for database nr exists, skipping... /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/blastp_Trinity_final_nr.out
    Mon Mar  7 10:02:12 2022: Verifying previous execution of database: /data1/IxoSca/database/bin/uniprot_sprot.dmnd...
    Mon Mar  7 10:02:12 2022: File for database uniprot_sprot exists, skipping... /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/blastp_Trinity_final_uniprot_sprot.out
    Mon Mar  7 10:02:12 2022: Verifying previous execution of database: /data1/IxoSca/database/bin/uniprot_trembl.dmnd...
    Mon Mar  7 10:02:12 2022: File for database uniprot_trembl exists, skipping... /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/blastp_Trinity_final_uniprot_trembl.out
    Mon Mar  7 10:02:12 2022: Success! Verified files for DIAMOND, continuing...
    Mon Mar  7 10:02:12 2022: Beginning to filter individual DIAMOND files...
    Mon Mar  7 10:02:12 2022: DIAMOND file located at /data1/IxoSca/HLongicornis/evidentialgene/entap_outfiles/similarity_search/DIAMOND/blastp_Trinity_final_Refseq.out being parsed

This is time consuming and unnecessary I think.... 
Is there a way to re-run the pipeline while avoiding 
a) Transcriptome (Amino acid) recopying to final transcriptome (run with previously generated file)
b) Re-run without re-parsing the DIAMOND output files (MOST IMPORTANT IN TIME SAVING)

**Comment by harta55** [comment]
Improvements have been made to speed of parsing files in latest versions. On quad core processor (~4 GHz) parsing all relevant files (expression analysis, frame selection, DIAMOND results, EggNOG results) of around 50k transcripts should take no more than 3 minutes.
