### ISSUE TITLE
Cleaner installation on linux systems

### ISSUE THREAD

**Issue by sanyalab** [harta55/EnTAP#74]
Hello,

I was wondering if the Entap installation code can be tweaked for a cleaner installation. I have the following configuration

OS: Fedora 8.7 (Ootpa)
GCC: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
python: 2.7.18
cmake: 3.28.1

No issues for `cmake CMakeLists.txt; cmake CMakeLists.txt -DCMAKE_INSTALL_PREFIX=/destination/dir` from the EnTap top dir.

Lots of warnings on doing `make install` after this. Some examples below

`[  5%] Building CXX object CMakeFiles/EnTAP.dir/src/ExceptionHandler.cpp.o`
`[  8%] Building CXX object CMakeFiles/EnTAP.dir/src/EntapGlobals.cpp.o`
`[ 10%] Building CXX object CMakeFiles/EnTAP.dir/src/EntapConfig.cpp.o`
`[ 13%] Building CXX object CMakeFiles/EnTAP.dir/src/EntapExecute.cpp.o`
`In file included from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/expression/ModRSEM.h:34,`
`                from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/ExpressionAnalysis.h:38,`
`                 from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/EntapExecute.h:36,`
`                from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/EntapExecute.cpp:30:`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h:1096:22: warning: unnecessary parentheses in declaration of ‘row’ [-Wparentheses]`
`                 char*(row[column_count]);`
`                      ^`

AND

`In file included from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/expression/ModRSEM.h:34,`
`                 from /home/sanyalab/SOFTWARE/EnTAP-1.0.1/src/expression/ModRSEM.cpp:30:`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h: In member function ‘virtual void io::error::can_not_open_file::format_error_message() const’:`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h:119:49: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 237 [-Wformat-truncation=]`
`                                                 "Can not open file \"%s\"."`
`                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h:118:54: note: ‘snprintf’ output between 22 and 277 bytes into a destination of size 256`
`                                         std::snprintf(error_message_buffer, sizeof(error_message_buffer),`
`                                         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`                                                 "Can not open file \"%s\"."`
`                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`                                                 , file_name);`
`                                                 ~~~~~~~~~~~~`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h:115:49: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 237 [-Wformat-truncation=]`
`                                                 "Can not open file \"%s\" because \"%s\"."`
`                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h:114:54: note: ‘snprintf’ output 33 or more bytes (assuming 288) into a destination of size 256`
`                                         std::snprintf(error_message_buffer, sizeof(error_message_buffer),`
`                                         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`                                                 "Can not open file \"%s\" because \"%s\"."`
`                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`                                                 , file_name, std::strerror(errno_value));`
`                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`/home/sanyalab/SOFTWARE/EnTAP-1.0.1/libs/fast-cpp-csv-parser/csv.h: In member function ‘virtual void` `io::error::line_length_limit_exceeded::format_error_message() const’:`

Can anything be done for a cleaner installation?

Thanks
Abhijit

**Comment by harta55** [comment]
These are warning messages from a library used by EnTAP (will not affect the compilation) and will be resolved in the next version

**Comment by harta55** [comment]
Changes made to latest version of EnTAP, 1.1.0
