### ISSUE TITLE
Only entap_results.tsv has the results

### ISSUE THREAD

**Issue by sanyalab** [harta55/EnTAP#75]
Hello,

The test data fan successfully via Entap, as mentioned by the tool. However, On closer examination, I find that the annotations are only present in file `entap_results.tsv`. Files `annotated.faa` and `annotated.fnn` have no annotations. They are unannotated, but fasta formatted. Same this is seen for `annotated_without_contam.faa` and `annotated_without_contam.fnn`. Is this a bug?

Abhijit

**Comment by harta55** [comment]
Hello Abhijit,
That is normal! the fnn/faa files contain the fasta formatted (for nucleotide/protein) versions of the sequences that were annotated through either similarity search or the ontology phase. Your entap_results.tsv file will have all of this information and more as tab-delim.
