### ISSUE TITLE
frame selection on amino acid fasta file

### ISSUE THREAD

**Issue by bioinfo17** [harta55/EnTAP#8]
Hi,
I'm trying to execute entap using an amino acid fasta file using the command line below:

  /EnTAP-v0.8.3-beta/EnTAP --runP -i file.faa -d /EnTAP-v0.8.3-beta/databases/uniprot_trembl.dmnd --paths /EnTAP-v0.8.3-beta/entap_config.txt --out-dir file_entap -c bacteria --ontology 0 --ontology 1 -t 16

For some reason, frame selection is being processed on the amino acid fasta file and pretty much all of the seqx are removed. In the manual, it states that if an amino acid file is provided as input and entap is ran with --runP, it should skip the frame selection step.

Any advice on this would be much appreciated, thanks

##updated to v0.8.4, working now.

**Comment by harta55** [comment]
Hello,

Apologies for the delay. Glad to hear it is working correctly now.
