### ISSUE TITLE
TransDecoder in Docker is missing perl dependency DB_File and URI::Escape

### ISSUE THREAD

**Issue by WaljaWanney** [harta55/EnTAP#80]
I wanted to drop by and share a problem with the docker image, as I've returned to using this fantastic tool in version 1.1.0 after initially discovering it in version 1.0.0 having the same problem back then. Other then that, EnTAP is running great, kudos to the team.

It seems that TransDecoder in the Docker image is missing its perl dependencies DB_File and URI::Escape. On the github page of TransDecoder they state that they are needed for optaining it: https://github.com/TransDecoder/TransDecoder/wiki 

**quote**
## Obtaining TransDecoder 

The latest release of TransDecoder can be found [here](https://github.com/TransDecoder/TransDecoder/releases).

>No compilation required - written in Perl, the favored scripting language of bioinformaticians back in the day.

The following Perl modules are needed and can be installed using cpanm like so:
```
curl -L https://cpanmin.us | perl - App::cpanminus
cpanm install DB_File
cpanm install URI::Escape
```

TransDecoder is also available for running via [Docker or Singularity](TransDecoder_Docker_or_Singularity) and includes BLAST+ and HMMER executables.
**quote end**

Maybe it is just me and I overlooked something but I fixed it in my case by editing the Dockerfile and installing the image from there rather then pulling.
Here are the relevant part with my addition added:
```
# Download TransDecoder (already there)
RUN git clone https://github.com/TransDecoder/TransDecoder.git \
&& cd TransDecoder \
&& git checkout TransDecoder-v5.7.1 \
&& cp -R . /usr/lib/TransDecoder-v5.7.1

# Download Perl dependency (my addition)
RUN curl -L https://cpanmin.us | perl - App::cpanminus\
&& cpanm install DB_File \
&& cpanm install URI::Escape
```
Hope my two cents here help and let me know if there is a better solution.

**Comment by harta55** [comment]
Thanks for the info! Haven't experienced this. Are you getting the TransDecoder error when building the Docker image or when running EnTAP? Can you send over the specific error as well?

**Comment by WaljaWanney** [comment]
Sure! I experience the error when running EnTAP.

```
Wed May 15 07:24:59 2024: Verifying software...
Wed May 15 07:24:59 2024: Verifying that Transdecoder is executable
Wed May 15 07:24:59 2024: Testing TransDecoder.LongOrfs executable...
Wed May 15 07:24:59 2024: Executing command: 
/TransDecoder/TransDecoder.LongOrfs --version
Wed May 15 07:24:59 2024: 
Std Err:
Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /TransDecoder/PerlLib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /TransDecoder/PerlLib/Gene_obj.pm line 3602.
BEGIN failed--compilation aborted at /TransDecoder/PerlLib/Gene_obj.pm line 3602.
Compilation failed in require at /TransDecoder/TransDecoder.LongOrfs line 16.
BEGIN failed--compilation aborted at /TransDecoder/TransDecoder.LongOrfs line 16.

Wed May 15 07:24:59 2024: ERROR invalid TransDecoder.LongOrfs execution
Wed May 15 07:24:59 2024: Killing Object - EntapDatabase
Wed May 15 07:25:08 2024: Killing Object - QueryData
Wed May 15 07:25:09 2024: QuerySequence data freed
Wed May 15 07:25:09 2024: Error code (10) not recognized
Wed May 15 07:25:09 2024: Error code: 10

Could not execute a test run of Transdecoder, be sure it's properly installed and the executable is correct
Wed May 15 07:25:09 2024: End - EnTAP
```
I specified the respective executables in the config for TransDecoder as:

```
#-------------------------------
# [frame_selection-transdecoder]
#-------------------------------
#Method to execute TransDecoder.LongOrfs. This may be the path to the executable or simply TransDecoder.LongOrfs
#type:string
transdecoder-long-exe=/usr/lib/TransDecoder-v5.7.1/TransDecoder.LongOrfs
#Method to execute TransDecoder.Predict. This may be the path to the executable or simply TransDecoder.Predict
#type:string
transdecoder-predict-exe=/usr/lib/TransDecoder-v5.7.1/TransDecoder.Predict
#-------------------------------
```
I run the command from outside of docker, but I get the same when testing TransDecoder in an interactive Docker session. Installing the perl modules/dependencies in the interactive docker session also fixes the issue within the session.

**Comment by harta55** [comment]
Thanks for the info! Just updated the Dockerfile to reflect the TransDecoder dependencies under new EnTAP version 1.1.1. Should be resolved now, closing issue
