### ISSUE TITLE
New release: Error in ini file

### ISSUE THREAD

**Issue by AlexGaithuma** [harta55/EnTAP#83]
I get the following error when configuring

command: ***EnTAP --config --run-ini entap_config.ini --entap-ini entap_run.params***

    Error code: 12
    Incorrect format in config file at line: data-generate=false

**Comment by harta55** [comment]
Hey! It looks like you just need to swap the files. `run-ini` should correspond to the `entap_run.params` file

**Comment by AlexGaithuma** [comment]
@harta55 thanks! 
Ps: The command was copied from entap.readthedocs.io

**Comment by juliayork** [comment]
Hey, I ran into the same problem. I switched the files and got the same error again. I ran: 
~/bin/EnTAP/EnTAP --config --run-ini ~/bin/EnTAP/entap_run.params --entap-ini ~/bin/EnTAP/entap_config.ini

it gives:
Parsing ini file at: /home/jmy/bin/EnTAP/entap_run.params
Parsing ini file at: /home/jmy/bin/EnTAP/entap_config.ini
Error code: 10

Invalid INI file format at line: data-generate=false

help please!!

**Comment by harta55** [comment]
Hey! Have not seen this. There aren't any weird formatting issues in the `entap_config.ini` around there? Including any trailing spaces or tabs, etc?

**Comment by harta55** [comment]
Docs updated to correct the config/ini file commands in the example with latest v1.2.0
