### ISSUE TITLE
New release: config fail

### ISSUE THREAD

**Issue by AlexGaithuma** [harta55/EnTAP#84]
I run the config command and it fails

***EnTAP --config --run-ini /data2/Alex_MulengaLab/tools/EnTAP-1.1.1/entap_run.params --entap-ini /data2/Alex_MulengaLab/tools/EnTAP-1.1.1/entap_config.ini***

    Parsing ini file at: /data2/Alex_MulengaLab/tools/EnTAP-1.1.1/entap_run.params
    Parsing ini file at: /data2/Alex_MulengaLab/tools/EnTAP-1.1.1/entap_config.ini
    ini files parsed, debug logging will continue at: entap_outfiles/debug_2024Y5M30D-10h46m46s.txt
    Error code: 10

    EggNOG DIAMOND database was not found at: /bin/eggnog_proteins.dmnd
    The DIAMOND test run failed.

**Comment by harta55** [comment]
The important part here is the "DIAMOND test run failed". I'd make sure you are correctly pointing to the DIAMOND executable in the entap config file. Also if you look at the debug file that entap printed, you'll see why DIAMOND failed

**Comment by AlexGaithuma** [comment]
I solved it by downloading the databases. and moving them to their respective folders.

    wget http://eggnog5.embl.de/download/emapperdb-5.0.2/eggnog_proteins.dmnd.gz
    pigz -d -p 16 eggnog_proteins.dmnd.gz
    wget https://treegenesdb.org/FTP/EnTAP/latest/databases/entap_database.db.gz 
    pigz -d -p 16 entap_database.db.gz
    wget https://treegenesdb.org/FTP/EnTAP/latest/databases/entap_database.bin.gz
    entap_database.bin.gz

**Comment by harta55** [comment]
The DIAMOND check was removed for EggNOG since it was no longer needed and the error message made more descriptive if errors occur with EggNOG in configuration. Change in v1.2.0
