### ISSUE TITLE
Version1.1.1:  interproscan database error

### ISSUE THREAD

**Issue by AlexGaithuma** [harta55/EnTAP#85]
I cant ran Interproscan on Entap.
my debug file is as below:

    interproscan-exe: /data2/Alex_MulengaLab/tools/interproscan-5.67-99.0/interproscan.sh
    protein: pfam
    hgt-donor: 
    hgt-recipient: 
    hgt-gff: 
    Fri May 31 10:19:21 2024: User has input a database at: /data2/Alex_MulengaLab/db/uniprot_trembl.dmnd
    Fri May 31 10:19:21 2024: User has input a database at: /data2/Alex_MulengaLab/db/Refseq.protein.dmnd
    Fri May 31 10:19:21 2024: User has input a database at: /data2/Alex_MulengaLab/db/uniprot_trembl.dmnd
    Fri May 31 10:19:21 2024: Verifying EnTAP database...
    Fri May 31 10:19:21 2024: Reading serialized database from: /data2/Alex_MulengaLab/db/bin/entap_database.bin Of type: 2
    Fri May 31 10:19:40 2024: Success!
    Fri May 31 10:19:40 2024: Spawn Object - QueryData
    Fri May 31 10:19:40 2024: Generating transcriptome mappings...
    Fri May 31 10:19:40 2024: Transcriptome Lines - START
    Fri May 31 10:19:40 2024: >JF1A_TRINITY_DN10022_c0_g1_i1.p1 JF1A_TRINITY_DN10022_c0_g1~~JF1A_TRINITY_DN10022_c0_g1_i1.p1  ORF type:internal len:108 (+),score=23.54,Defensin_4|PF07936.12|6.1e+03,Defensin_4|PF07936.12|0.15,Defensin_4|PF07936.12|6.8e+03 JF1A_TRINITY_DN10022_c0_g1_i1:2-322(+)
    Fri May 31 10:19:40 2024: AGGAAAAAGGGTTCTCGAGATTCGGTGGGCCTTACAGTGTCAGCTAATGGAATTCATTGG
    Fri May 31 10:19:40 2024: CGAAGAGGAACTGGACACATTCAGACTGATGATGATGTTGGTATTGTCATGGAATGCAGT
    Fri May 31 10:19:40 2024: GATGATTGGTGGGCCTTTGATACTGAGATTGTTCGACCATCTGATATTCTTATACTGTCT
    Fri May 31 10:19:40 2024: AGTGAGAAGCTGAAAGCCTCAAGTGGGGTTTATTGGATGTTTTATTCGGGATGCAACTCG
    Fri May 31 10:19:40 2024: GATGAGATAAATGTTCCCCAAGTGTTGCTTGGGAACCCTTGGAAGTTTGAGGAGACTTGC
    Fri May 31 10:19:40 2024: CTTGAATCTACTCTTTTTAGG
    Fri May 31 10:19:40 2024: >JF1A_TRINITY_DN10032_c0_g1_i1.p1 JF1A_TRINITY_DN10032_c0_g1~~JF1A_TRINITY_DN10032_c0_g1_i1.p1  ORF type:5prime_partial len:102 (+),score=5.52 JF1A_TRINITY_DN10032_c0_g1_i1:1-306(+)
    Fri May 31 10:19:40 2024: AATGTGCCCTTGTTAATGTTTCCGTTCATGATAACGAACTGGCTTCTTACAGTTTTGTCA
    Fri May 31 10:19:40 2024: Transcriptome Lines - END
    Fri May 31 10:19:40 2024: Success!
    Fri May 31 10:19:40 2024: Verifying input flag fpkm
    Fri May 31 10:19:40 2024: Verifying input flag qcoverage
    Fri May 31 10:19:40 2024: Verifying input flag tcoverage
    Fri May 31 10:19:40 2024: Verifying input flag ontology
    Fri May 31 10:19:40 2024: Verifying input flag level
    Fri May 31 10:19:40 2024: Killing Object - EntapDatabase
    Fri May 31 10:19:45 2024: Killing Object - QueryData
    Fri May 31 10:19:45 2024: QuerySequence data freed
    Fri May 31 10:19:45 2024: Error code (10) not recognized
    Fri May 31 10:19:45 2024: Error code: 10

    InterProScan selected, but invalid databases input!
    Fri May 31 10:19:45 2024: End - EnTAP

**Comment by AlexGaithuma** [comment]
fixed issue by creating conda environment and installing pytho 2.7 using

    conda env update -n my_env --file python27.yml
my .yml file contains

    name: python27
    dependencies:
    - python=2.7
    - virtualenv
    - ipython
    - numpy
    - scipy

**Comment by harta55** [comment]
Hey! Did you modify the config file `interproscan-db` or `protein` (if using older version) commands in between runs? By default, there aren't databases listed for those commands which would give you an error.

**Comment by chenyidai95** [comment]
Hi! I guess the problem is at the database flag "morbidblite" in the file "entap_run.params". When I put all database:
interproscan-db=tigrfam
interproscan-db=sfld
interproscan-db=prodom
interproscan-db=hamap
interproscan-db=pfam
interproscan-db=smart
interproscan-db=cdd
interproscan-db=prositeprofiles
interproscan-db=prositepatterns
interproscan-db=superfamily
interproscan-db=prints
interproscan-db=panther
interproscan-db=gene3d
interproscan-db=pirsf
interproscan-db=coils
interproscan-db=morbidblite
in "entap_run.params", the error message "Error code: 10 InterProScan selected, but invalid databases input!" was shown.
However, when I removed the final one "interproscan-db=morbidblite", the EnTap worked.

**Comment by harta55** [comment]
Corrected EnTAP not recognizing all InterProScan databases in latest version 1.4.0
