### ISSUE TITLE
Adding Ref-seq diamond database for EnTAP

### ISSUE THREAD

**Issue by Artifice120** [harta55/EnTAP#97]
Morning,

Just want to know for sure, after downloading the complete ref-seq database which files should be concatenated for the diamond database? For example a single entry/partition will have a set of genomic files, bna files, protein files, and rna files as seen below.

```
complete.1139.1.genomic.fna.gz  complete.1139.3.genomic.fna.gz  complete.1139.5.genomic.fna.gz  complete.1139.bna.gz           complete.1139.protein.faa.gz   complete.1139.rna.fna.gz
complete.1139.2.genomic.fna.gz  complete.1139.4.genomic.fna.gz  complete.1139.6.genomic.fna.gz  complete.1139.genomic.gbff.gz  complete.1139.protein.gpff.gz  complete.1139.rna.gbff.gz

```
I assume that only the protein files are needed for the homology searches, but I just want to make sure in case another files is needed for taxonomy.

Thanks

**Comment by harta55** [comment]
Hello! Correct, you'll just want to concatenate the 'protein.faa' files. Something like this should do the trick:
`wget -r -A '*.protein.faa.gz' ftp://ftp.ncbi.nlm.nih.gov/refseq/release/complete/
        gunzip ./ftp.ncbi.nlm.nih.gov/refseq/release/complete/*.gz
        cat ./ftp.ncbi.nlm.nih.gov/refseq/release/complete/*.faa > refseq_complete.protein.faa
        rm -rf ftp.ncbi.nlm.nih.gov`

**Comment by Artifice120** [comment]
Thanks

**Comment by harta55** [comment]
Yes it should be formatted like this as an example:
`>XP_020753639.1 pro-neuregulin-3, membrane-bound isoform isoform X2 [Odocoileus virginianus texanus]`
EnTAP will pull the taxon within the brackets.
